import { Dosis } from "next/font/google";
import "./globals.css";
import HeadBar from "./HeadBar";

export const DosisFont = Dosis({
  subsets: ["vietnamese"],
  weight: "500",
});

export const metadata = {
  title: "AHP FILM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased h-screen flex flex-col text-[20px] ${DosisFont.className}`}>
        <HeadBar />
        {children}
      </body>
    </html>
  );
}
