import { Dosis } from "next/font/google";
import "./globals.css";
import HeadBar from "./HeadBar";
import { Context } from "./Context";
import Warning from "./Warning";

export const DosisFont = Dosis({
  subsets: ["vietnamese"],
  weight: "500",
});

export const metadata = {
  title: "AHP FILM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased h-screen flex flex-col overflow-auto scroll-box text-[20px] ${DosisFont.className}`}
      >
        <Context>
          <HeadBar />
          <Warning/>
          {children}
        </Context>
      </body>
    </html>
  );
}
